### ISSUE TITLE
Error when using 'pull'

### ISSUE THREAD

**Issue by siva-mudiyanur** [tokern/dbcat#21]
Hi,

First of all, thanks for setting up a opensource platform for data lineage. I tried to setup config file and executed the pull command on dbcat but it give me the following error: 

```
dbcat pull
Traceback (most recent call last):
  File "d:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python\Scripts\dbcat.exe\__main__.py", line 7, in <module>
  File "d:\python\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "d:\python\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\python\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\python\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\python\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\python\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "d:\python\lib\site-packages\dbcat\__main__.py", line 129, in pull_cli
    catalog = Catalog(**config["catalog"])
TypeError: __init__() missing 1 required positional argument: 'database' 
```

Please let me know if I missed anything, thank you!

**Comment by siva-mudiyanur** [comment]
I also tried using --config-dir option and got a different error: 

```
C:\Users\siva\.dbcat>dbcat --config-dir config pull
Traceback (most recent call last):
  File "d:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python\Scripts\dbcat.exe\__main__.py", line 7, in <module>
  File "d:\python\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "d:\python\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\python\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\python\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\python\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\python\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "d:\python\lib\site-packages\dbcat\__main__.py", line 124, in pull_cli
    with open(config_file, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sivamudi\\.dbcat\\config\\config'
```

**Comment by siva-mudiyanur** [comment]
turns out the config template is missing database value for catalog in the template when was created as part of init. please add it to resolve the issue.

**Comment by vrajat** [comment]
Thanks for reporting this bug. I havent maintained the CLI and added tests for it. I use this as a library in [data-lineage](https://github.com/tokern/data-lineage) and piicatcher(https://github.com/tokern/piicatcher).
I am considering removing CLI and only support it as a library.
 
Do you think the CLI is useful? Will you use dbcat as a stand-alone application?

**Comment by siva-mudiyanur** [comment]
I was only using it to setup for data-lineage.CLI may not be useful but the tables created in postgres could be useful, I will provide more feedback once I setup the data lineage.
